---
-
  name: Send IOS command
  hosts: R1
  gather_facts: no

  tasks:

  - name: Send show commands
    template:
      src: './template.j2'
      dest: './res.cfg'

#    with_items:
#      - {hostname: 'r1'}