routers:
  hosts:
    R1:
      ansible_host: 1.1.1.1
    R2:
      ansible_host: 2.2.2.2
    R3:
      ansible_host: 3.3.3.3
    R4:
      ansible_host: 4.4.4.4
    R5:
      ansible_host: 5.5.5.5
    R6:
      ansible_host: 6.6.6.6
    R7:
      ansible_host: 7.7.7.7
    R8:
      ansible_host: 8.8.8.8

all_routers:
  children:
    routers
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become_password: cisco